### ISSUE TITLE
Trouble deploying

### ISSUE THREAD

**Issue by jessleenyc** [jessleenyc/vimeo#6]
Hi! 

I've set all my env variables in heroku and the only porential error I'm seeing in my heroku logs is "no such file or directory, open .env' ? 

Please advise!!

**Comment by jessleenyc** [comment]
just refreshed the page again and it works now?

**Comment by jessleenyc** [comment]
closed

**Comment by phlco** [comment]
Closed! Did you get it? I'm imagining you wouldn't use .env in production.
